[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 3

[deploy.env]
NODE_ENV = "production" 